/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as SavedRouteImport } from './pages/saved'
import { Route as NeoRouteImport } from './pages/neo'
import { Route as EpicRouteImport } from './pages/epic'
import { Route as IndexRouteImport } from './pages/index'
import { Route as LibraryIndexRouteImport } from './pages/library/index'
import { Route as ApodIndexRouteImport } from './pages/apod/index'
import { Route as LibraryIdRouteImport } from './pages/library/$id'
import { Route as ApodDateRouteImport } from './pages/apod/$date'

const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const NeoRoute = NeoRouteImport.update({
  id: '/neo',
  path: '/neo',
  getParentRoute: () => rootRouteImport,
} as any)
const EpicRoute = EpicRouteImport.update({
  id: '/epic',
  path: '/epic',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApodIndexRoute = ApodIndexRouteImport.update({
  id: '/apod/',
  path: '/apod/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIdRoute = LibraryIdRouteImport.update({
  id: '/library/$id',
  path: '/library/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApodDateRoute = ApodDateRouteImport.update({
  id: '/apod/$date',
  path: '/apod/$date',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/epic': typeof EpicRoute
  '/neo': typeof NeoRoute
  '/saved': typeof SavedRoute
  '/apod/$date': typeof ApodDateRoute
  '/library/$id': typeof LibraryIdRoute
  '/apod/': typeof ApodIndexRoute
  '/library/': typeof LibraryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/epic': typeof EpicRoute
  '/neo': typeof NeoRoute
  '/saved': typeof SavedRoute
  '/apod/$date': typeof ApodDateRoute
  '/library/$id': typeof LibraryIdRoute
  '/apod': typeof ApodIndexRoute
  '/library': typeof LibraryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/epic': typeof EpicRoute
  '/neo': typeof NeoRoute
  '/saved': typeof SavedRoute
  '/apod/$date': typeof ApodDateRoute
  '/library/$id': typeof LibraryIdRoute
  '/apod/': typeof ApodIndexRoute
  '/library/': typeof LibraryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/epic'
    | '/neo'
    | '/saved'
    | '/apod/$date'
    | '/library/$id'
    | '/apod/'
    | '/library/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/epic'
    | '/neo'
    | '/saved'
    | '/apod/$date'
    | '/library/$id'
    | '/apod'
    | '/library'
  id:
    | '__root__'
    | '/'
    | '/epic'
    | '/neo'
    | '/saved'
    | '/apod/$date'
    | '/library/$id'
    | '/apod/'
    | '/library/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EpicRoute: typeof EpicRoute
  NeoRoute: typeof NeoRoute
  SavedRoute: typeof SavedRoute
  ApodDateRoute: typeof ApodDateRoute
  LibraryIdRoute: typeof LibraryIdRoute
  ApodIndexRoute: typeof ApodIndexRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neo': {
      id: '/neo'
      path: '/neo'
      fullPath: '/neo'
      preLoaderRoute: typeof NeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epic': {
      id: '/epic'
      path: '/epic'
      fullPath: '/epic'
      preLoaderRoute: typeof EpicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apod/': {
      id: '/apod/'
      path: '/apod'
      fullPath: '/apod/'
      preLoaderRoute: typeof ApodIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$id': {
      id: '/library/$id'
      path: '/library/$id'
      fullPath: '/library/$id'
      preLoaderRoute: typeof LibraryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apod/$date': {
      id: '/apod/$date'
      path: '/apod/$date'
      fullPath: '/apod/$date'
      preLoaderRoute: typeof ApodDateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EpicRoute: EpicRoute,
  NeoRoute: NeoRoute,
  SavedRoute: SavedRoute,
  ApodDateRoute: ApodDateRoute,
  LibraryIdRoute: LibraryIdRoute,
  ApodIndexRoute: ApodIndexRoute,
  LibraryIndexRoute: LibraryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
